<?php

namespace AppBundle\Repository;

/**
 * AdvertMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
