<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13v4tpt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13v4tpt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container13v4tpt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container13v4tpt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container13v4tpt\appDevDebugProjectContainer();
